# Generated by Django 2.0.3 on 2018-03-07 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(verbose_name='date donated')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('social_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.People'),
        ),
    ]
