# Generated by Django 2.0.3 on 2018-03-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20180310_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
