# Generated by Django 2.0.3 on 2018-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_number',
            field=models.CharField(max_length=14),
        ),
    ]
